### ISSUE TITLE
Problems using the library

### ISSUE THREAD

**Issue by javiersorucol** [Perevalov/LinguaF#15]
Hi! I've installing the library by using pip, but I'm getting an error when trying to use the example in the readme, I'm trying to run:

```
from linguaf import descriptive_statistics as ds

documents = [
    "Pain and suffering are always inevitable for a large intelligence and a deep heart. The really great men must, I think, have great sadness on earth.",
    "To go wrong in one's own way is better than to go right in someone else's.",
    "The darker the night, the brighter the stars, The deeper the grief, the closer is God!"
]

print(ds.words_per_sentence(documents))
```

and I get:
```
Traceback (most recent call last):
  File "x.py", line 1, in <module>
    from linguaf import descriptive_statistics as ds
  File "C:\Users\javi\anaconda3\lib\site-packages\linguaf\descriptive_statistics.py", line 26, in <module>
    STOPWORDS[language] = __load_json(
  File "C:\Users\javi\anaconda3\lib\site-packages\linguaf\__init__.py", line 10, in __load_json
    data = json.load(f)
  File "C:\Users\javi\anaconda3\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\javi\anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 98: character maps to <undefined>

```
I've tried to install the package from github too and got the same result, can you give me a hand?

**Comment by javiersorucol** [comment]
I've fixed it by specifying encoding as utf-8 in the function load_json in the __init__.py file of the library.

```
def __load_json(filepath):
    data = None
    with open(filepath, encoding="utf8") as f:
        data = json.load(f)
    return data

```
